FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/
# COPY nginx.conf /etc/nginx/conf.d/
# VOLUME /var/log/nginx/log

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/
#COPY nginx.conf /etc/nginx/conf.d/
